
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "krbddfvnclrgcycgdxpu"
# The URL of your Supabase hosted API.
# Overrides the SUPABASE_URL environment variable.
api_url = "https://krbddfvnclrgcycgdxpu.supabase.co/rest/v1"

[api]
# Disables the default migrations patterns. Set to `false` to skip the version check.
enabled = true
# Port to use when serving the API locally.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows to return when listing. The absolute maximum is 1000.
max_rows = 1000

[api.rate_limits]
# Allow a burst of N concurrent requests.
burst = 1000
# Refill the bucket at a rate of N requests per second.
rate = 100
# Optionally, configure separate burst and rate limits for anonymous (not signed-in) requests.
# Defaults to applying the same values as when authenticated.
unauthenticated_burst = 100
unauthenticated_rate = 10

# Configure the edge functions deployment
[functions]
[functions.send-otp]
verify_jwt = true
[functions.check-leaked-password]
verify_jwt = false

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use when serving Studio locally.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post-authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[analytics]
# Enable/disable collection of analytics data.
enabled = false

# Configure PostgREST, the solution used by Supabase API
[postgrest]
# Enable/disable the PostgREST service. Defaults to true.
enabled = true

# Configure Kong, a proxy used by the API and Edge Functions
[kong]
# Enable/disable the Kong service.
enabled = true
