
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkwfkaeggmcaivynnbqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrd2ZrYWVnZ21jYWl2eW5uYnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDU4OTgsImV4cCI6MjA2MzQyMTg5OH0.LZ0OfLvRJyigWxafjJ_PpCg4TjyG_SWUzUM65vyluBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Intercept fetch requests to redirect edge function calls
const originalFetch = window.fetch;
window.fetch = async (input: RequestInfo | URL, init?: RequestInit) => {
  const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
  
  // Redirect API calls to Supabase edge functions
  if (url.startsWith('/api/v1/')) {
    const functionName = url.replace('/api/v1/', '');
    const newUrl = `${SUPABASE_URL}/functions/v1/${functionName}`;
    
    const newInput = typeof input === 'string' ? newUrl : 
                     input instanceof URL ? new URL(newUrl) :
                     new Request(newUrl, input);
    
    return originalFetch(newInput, init);
  }
  
  return originalFetch(input, init);
};
