
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krbddfvnclrgcycgdxpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyYmRkZnZuY2xyZ2N5Y2dkeHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDg3NjcsImV4cCI6MjA2MzMyNDc2N30.qG6aLqV-IHCDAmBqp_PCOl8HD9KTBnRmk7KWe3DaJYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Export SUPABASE_URL for convenience
export { SUPABASE_URL };
